services:
  web:
    build: .
    container_name: flight_booking_web
    ports:
      - "8082:80"        # ðŸ”´ NOT 8080 (8080 is Jenkins)
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: flight_booking
    restart: always

  db:
    image: mysql:8.0
    container_name: flight_booking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flight_booking
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
